services:
  flask-api:
    build: .
    container_name: flask-api-v2
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASS=password
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: